### ISSUE TITLE
How to make it multiuser

### ISSUE THREAD

**Issue by hapishyguy** [litrik/displayer#22]
I was able to build the android app and the desktop app. How can we make it multi user / Multi tenant? Any ideas, any guidance?

**Comment by litrik** [comment]
Displayer is (currently) only the _player_ part. The editing and storing of the display file itself is kept out-of-scope (on purpose).

In my own use case, I store the display file in a [Github repo](https://github.com/kcbj/kcbj-displayer). That way I can give edit rights to other people (when the need arises).

Can you describe a bit more in detail which functionality you are looking for?

**Comment by hapishyguy** [comment]
Where is the display file and how can I store and share edit from a repository.
I understand partly that display file can be in a respository and then access rights given accordingly. But where is the file. Any point out would be appreciated.
Can layout be changed as well?

**Comment by litrik** [comment]
The display file is a JSON file that...
-  is stored anywhere on the internet. Then you can tell Displayer to [load the remote display file](https://github.com/litrik/displayer/tree/main/docs/samples).For example, all [sample display files](docs/samples/index.md) are stored in [docs/samples](https://github.com/litrik/displayer/tree/main/docs/samples). 
- is stored on your own machine. Then you can [upload the display file](docs/samples/index.md) to Displayer (after enabling the [admin server](docs/samples/index.md))

**Comment by hapishyguy** [comment]
I get it about the display file. Is there to send media from outside to the app?

**Comment by litrik** [comment]
You can't really "send" something to the app. But the _display file_ you are playing can point to remote images. See the [images sample](https://github.com/litrik/displayer/blob/main/docs/samples/images.json).
